dist: xenial
language: ruby

before_install:
  - bundle config without 'development'

branches:
  only:
    - master

matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rbx-2
  include:
    - rvm: 2.6.4
    - rvm: 2.5.6
    - rvm: 2.4.7
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rbx-2
