version: "3"
services:
  twurl:
    build:
        context: ..
        dockerfile: ./.devcontainer/Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
        - ../:/usr/src/app
